GET http://localhost:3001/api/
###
POST http://localhost:3001/api/catagory
Content-Type: application/json

{
    "catagory_id":16,
    "child_catagories":[11, 12, 13],
    "product_list":[101, 102, 103]
}
###
GET http://localhost:3001/api/catagory
###
GET http://localhost:3001/api/catagory/10
###
GET http://localhost:3001/api/product
###
GET http://localhost:3001/api/product/101
###
POST http://localhost:3001/api/product
Content-Type: application/json

{
    "product_id":123,
    "product_catagories":[15, 16, 22]
}
###
